// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://franshalsmuseum.nl/en/collection?onView=false
// Generated: 2026-06-11T15:55:09.185Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary';
export type ColorHex  = '#001317' | '#fafafa' | '#000000' | '#fecd8c';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Rubik';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '700' | '600';

export type SpacingToken = '4px' | '56px' | '80px' | '240px';

export type RadiusToken = '12px' | '24px' | '36px';

export type DurationToken = '150ms' | '200ms' | '400ms' | '1000ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
