// Motion One presets — generated by designlang (motionlang)
// Source: https://franshalsmuseum.nl/en/collection?onView=false
// 2026-06-11T15:55:09.186Z
//
//   import { animate } from 'motion';
//   import { animations, easings, durations } from './franshalsmuseum.nl-motion.one.js';
//
//   animations.fadeIn('#hero');
//   animations.slideUp('.card', { delay: 0.1 });

/** Easing curves extracted from the live page, as Motion One cubic-bezier arrays. */
export const easings = {
  custom1: [0.42, 0, 0, 1], // 42× on page
  easeIn: [0.4, 0, 1, 1], // 41× on page
  easeOut: [0, 0, 0.2, 1], // 36× on page
  custom4: [0.4, 0, 0.2, 1], // 19× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.15,
  sm: 0.2,
  md: 0.4,
  xl: 1,
};

/** Motion One spring options — pass as the `type: 'spring'` block of an animate() call. */
export const springs = {
  soft: { type: 'spring', stiffness: 320, damping: 30, mass: 1 },
};

/** No on-page @keyframes were attached to elements; emit empty for shape parity. */
export const keyframes = {};

/** Animate-on-call helpers. Each takes a Motion One target + optional override. */
import { animate } from 'motion';

const _t = { duration: 0.4, easing: easings.custom1 };

export const animations = {
  fadeIn: (target, opts = {}) =>
    animate(target, { opacity: [0, 1] }, { ..._t, ...opts }),
  fadeOut: (target, opts = {}) =>
    animate(target, { opacity: [1, 0] }, { ..._t, ...opts }),
  slideUp: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], y: [16, 0] }, { ..._t, ...opts }),
  slideDown: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], y: [-16, 0] }, { ..._t, ...opts }),
  scaleIn: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], scale: [0.96, 1] }, { ..._t, ...opts }),
  pop: (target, opts = {}) =>
    animate(target, { scale: [0.9, 1] }, { ...springs.soft, ...opts }),
};

/** Site uses scroll- or view-timeline. Helpers wired to Motion One's `inView` / `scroll`. */
import { inView, scroll } from 'motion';

export const enterOnView = (target, variant = animations.slideUp) =>
  inView(target, (el) => { variant(el.target); });

export const parallaxY = (target, distance = 80) =>
  scroll(animate(target, { y: [0, -distance] }, { easing: 'linear' }));

export default { easings, durations, springs, keyframes, animations };
